import { useState } from "react";
import { Printer, Download, Bookmark, Send, BookmarkCheck, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { useAuth } from "@/contexts/AuthContext";
import { supabase } from "@/integrations/supabase/client";
import { useNavigate } from "react-router-dom";
import type { EducationalGuide } from "@/data/educationalGuides";

interface GuideActionsProps {
  guide: EducationalGuide;
  categoryTitle?: string;
}

function buildPrintHTML(guide: EducationalGuide, categoryTitle?: string) {
  return `<!DOCTYPE html>
<html><head>
<title>${guide.title} — Decoded Justice</title>
<style>
  body { font-family: Georgia, serif; line-height: 1.7; max-width: 7.5in; margin: 0 auto; padding: 0.75in; color: #1F2933; }
  h1 { font-size: 22px; margin-bottom: 4px; }
  h2 { font-size: 16px; margin-top: 28px; border-bottom: 1px solid #ccc; padding-bottom: 4px; }
  .subtitle { color: #616E7C; font-size: 13px; margin-bottom: 24px; }
  ul { padding-left: 20px; }
  li { margin-bottom: 6px; font-size: 14px; }
  p { font-size: 14px; }
  .disclaimer { margin-top: 40px; padding-top: 12px; border-top: 1px solid #ccc; font-size: 11px; color: #7B8794; }
  @media print { body { padding: 0; } }
</style>
</head><body>
<h1>${guide.title}</h1>
<p class="subtitle">${categoryTitle ? categoryTitle + " · " : ""}${guide.readTime} · Decoded Justice</p>

<h2>Before You Start</h2>
<p>${guide.beforeYouStart.grounding}</p>
<p><em>${guide.beforeYouStart.consent}</em></p>

<h2>What This System Is</h2>
<p>${guide.whatThisSystemIs.description}</p>
<p><strong>Who Runs It:</strong> ${guide.whatThisSystemIs.whoRunsIt}</p>
<p><strong>What It Controls:</strong> ${guide.whatThisSystemIs.whatItControls}</p>

<h2>Why It Feels Confusing</h2>
<p>${guide.whyConfusing.explanation}</p>
<ul>${guide.whyConfusing.structuralReasons.map(r => `<li>${r}</li>`).join("")}</ul>

<h2>What Usually Happens</h2>
<ul>${guide.whatUsuallyHappens.map((s, i) => `<li><strong>${i + 1}.</strong> ${s}</li>`).join("")}</ul>

<h2>What Success Actually Looks Like</h2>
<p>${guide.successReframe.reality}</p>
<ul>${guide.successReframe.examples.map(e => `<li>${e}</li>`).join("")}</ul>

<h2>What People Often Misunderstand</h2>
<ul>${guide.misunderstandings.traps.map(t => `<li>${t}</li>`).join("")}</ul>

<h2>What You Can Do Safely</h2>
<ul>${guide.safeSteps.map((s, i) => `<li><strong>${i + 1}.</strong> ${s}</li>`).join("")}</ul>

<h2>When It's Time to Escalate</h2>
<p>${guide.escalation.explanation}</p>
<ul>${guide.escalation.signs.map(s => `<li>${s}</li>`).join("")}</ul>

<h2>A Final Note</h2>
<p>${guide.closing.reassurance}</p>

<div class="disclaimer">This document is for educational purposes only and does not constitute legal advice. For legal guidance, consult a qualified attorney. Generated by Decoded Justice.</div>
</body></html>`;
}

export function GuideActions({ guide, categoryTitle }: GuideActionsProps) {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [isSaved, setIsSaved] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [isChecked, setIsChecked] = useState(false);

  // Check if already saved on mount
  if (user && !isChecked) {
    setIsChecked(true);
    supabase
      .from("justice_place_bookmarks")
      .select("id")
      .eq("user_id", user.id)
      .eq("resource_type", "guide")
      .eq("resource_id", guide.id)
      .maybeSingle()
      .then(({ data }) => {
        if (data) setIsSaved(true);
      });
  }

  const handlePrint = () => {
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;
    printWindow.document.write(buildPrintHTML(guide, categoryTitle));
    printWindow.document.close();
    printWindow.print();
  };

  const handleDownloadPDF = () => {
    const printWindow = window.open("", "_blank");
    if (!printWindow) {
      toast.error("Please allow pop-ups to download");
      return;
    }
    printWindow.document.write(buildPrintHTML(guide, categoryTitle));
    printWindow.document.close();
    // Give browser a moment to render, then trigger print (user can "Save as PDF")
    setTimeout(() => {
      printWindow.print();
      toast.info("Use 'Save as PDF' in the print dialog to download.");
    }, 300);
  };

  const handleSave = async () => {
    if (!user) {
      navigate(`/auth?redirect=/guide/${guide.id}`);
      return;
    }

    setIsSaving(true);
    try {
      if (isSaved) {
        await supabase
          .from("justice_place_bookmarks")
          .delete()
          .eq("user_id", user.id)
          .eq("resource_type", "guide")
          .eq("resource_id", guide.id);
        setIsSaved(false);
        toast.success("Guide removed from your case");
      } else {
        await supabase.from("justice_place_bookmarks").insert({
          user_id: user.id,
          resource_type: "guide",
          resource_id: guide.id,
          resource_title: guide.title,
          resource_url: `/guide/${guide.id}`,
        });
        setIsSaved(true);
        toast.success("Guide saved to your case");
      }
    } catch {
      toast.error("Something went wrong");
    } finally {
      setIsSaving(false);
    }
  };

  const handleSend = async () => {
    const shareUrl = `${window.location.origin}/guide/${guide.id}`;
    if (navigator.share) {
      try {
        await navigator.share({
          title: `${guide.title} — Decoded Justice`,
          text: `Educational guide: ${guide.title}`,
          url: shareUrl,
        });
        return;
      } catch {
        // fall through to clipboard
      }
    }
    await navigator.clipboard.writeText(shareUrl);
    toast.success("Link copied to clipboard");
  };

  return (
    <div className="flex flex-wrap gap-2">
      <Button variant="outline" size="sm" onClick={handlePrint} className="gap-2 text-xs">
        <Printer className="w-3.5 h-3.5" />
        Print Guide
      </Button>
      <Button variant="outline" size="sm" onClick={handleDownloadPDF} className="gap-2 text-xs">
        <Download className="w-3.5 h-3.5" />
        Download PDF
      </Button>
      <Button
        variant={isSaved ? "soft" : "outline"}
        size="sm"
        onClick={handleSave}
        disabled={isSaving}
        className="gap-2 text-xs"
      >
        {isSaving ? (
          <Loader2 className="w-3.5 h-3.5 animate-spin" />
        ) : isSaved ? (
          <BookmarkCheck className="w-3.5 h-3.5" />
        ) : (
          <Bookmark className="w-3.5 h-3.5" />
        )}
        {isSaved ? "Saved" : "Save to My Case"}
      </Button>
      <Button variant="outline" size="sm" onClick={handleSend} className="gap-2 text-xs">
        <Send className="w-3.5 h-3.5" />
        Send Guide
      </Button>
    </div>
  );
}
