import { Link } from "react-router-dom";
import { AlertCircle, Scale, ShieldCheck } from "lucide-react";
import { Layout } from "@/components/layout/Layout";
import { Button } from "@/components/ui/button";
import { Disclaimer as DisclaimerNotice } from "@/components/shared/Disclaimer";

export default function DisclaimerPage() {
  return (
    <Layout>
      <div className="container py-12 lg:py-20">
        <div className="max-w-3xl mx-auto">
          {/* Header */}
          <div className="text-center mb-12">
            <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-gradient-to-br from-primary/20 to-primary/5 mb-6">
              <Scale className="w-8 h-8 text-primary" />
            </div>
            <h1 className="text-3xl md:text-4xl font-serif font-semibold text-foreground mb-4">
              Legal Disclaimer
            </h1>
            <p className="text-muted-foreground">
              Important information about the nature and limitations of this platform.
            </p>
          </div>

          <div className="space-y-8">
            {/* Not Legal Advice */}
            <section className="p-6 rounded-2xl bg-card border border-border">
              <div className="flex items-center gap-3 mb-4">
                <AlertCircle className="w-5 h-5 text-primary" />
                <h2 className="text-lg font-semibold text-foreground">Not Legal Advice</h2>
              </div>
              <div className="space-y-3 text-muted-foreground leading-relaxed">
                <p>Decoded Justice is not a law firm and does not provide legal advice, legal representation, or legal analysis. The information provided on this platform is for educational purposes only and should not be construed as legal advice.</p>
                <p>No information on this platform — including content generated by AI-powered tools — should be relied upon as a substitute for professional legal counsel.</p>
              </div>
            </section>

            {/* No Attorney-Client Relationship */}
            <section className="p-6 rounded-2xl bg-card border border-border">
              <div className="flex items-center gap-3 mb-4">
                <ShieldCheck className="w-5 h-5 text-primary" />
                <h2 className="text-lg font-semibold text-foreground">No Attorney-Client Relationship</h2>
              </div>
              <div className="space-y-3 text-muted-foreground leading-relaxed">
                <p>Use of this platform does not create an attorney-client relationship between you and Decoded Justice, its creators, or any affiliated parties.</p>
                <p>If you need legal advice, please consult with a qualified attorney licensed in your jurisdiction.</p>
              </div>
            </section>

            {/* No Outcome Predictions */}
            <section className="p-6 rounded-2xl bg-card border border-border">
              <div className="flex items-center gap-3 mb-4">
                <AlertCircle className="w-5 h-5 text-primary" />
                <h2 className="text-lg font-semibold text-foreground">No Outcome Predictions</h2>
              </div>
              <div className="space-y-3 text-muted-foreground leading-relaxed">
                <p>This platform does not predict, guarantee, or imply any particular outcome for any legal, administrative, or civil rights matter. Every situation is unique, and outcomes depend on facts, jurisdiction, and many other factors beyond the scope of this platform.</p>
              </div>
            </section>

            {/* AI-Generated Content */}
            <section className="p-6 rounded-2xl bg-card border border-border">
              <div className="flex items-center gap-3 mb-4">
                <Scale className="w-5 h-5 text-primary" />
                <h2 className="text-lg font-semibold text-foreground">AI-Generated Content</h2>
              </div>
              <div className="space-y-3 text-muted-foreground leading-relaxed">
                <p>Some features on this platform use artificial intelligence to generate educational content, summaries, and organizational suggestions. AI-generated content may contain errors or omissions and should always be verified independently.</p>
                <p>AI output is not a substitute for professional judgment or legal analysis.</p>
              </div>
            </section>

            {/* Accuracy */}
            <section className="p-6 rounded-2xl bg-secondary/30 border border-border/50">
              <p className="text-muted-foreground leading-relaxed text-center">
                While we strive for accuracy, laws, procedures, and systems change over time. Always verify information with current, authoritative sources and qualified professionals.
              </p>
            </section>
          </div>

          <div className="text-center mt-10">
            <Button variant="outline" size="lg" asChild>
              <Link to="/about">Back to About</Link>
            </Button>
          </div>

          <div className="mt-12 pt-8 border-t border-border">
            <DisclaimerNotice className="justify-center" />
          </div>
        </div>
      </div>
    </Layout>
  );
}
