// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-cases.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-cases.ts
var list_cases_default = defineTool({
  name: "list_cases",
  title: "List cases",
  description: "List the signed-in user's cases in their Justice Place workspace.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Maximum cases to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("justice_place_cases").select("id, case_name, case_status, issue_type, county, incident_month_year, created_at").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { cases: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-timeline-entries.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var list_timeline_entries_default = defineTool2({
  name: "list_timeline_entries",
  title: "List timeline entries",
  description: "List the signed-in user's case timeline entries in chronological order.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).optional().describe("Maximum entries to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("timeline_entries").select("id, title, description, event_date, created_at").order("event_date", { ascending: true }).limit(limit ?? 25);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { entries: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/add-timeline-entry.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var add_timeline_entry_default = defineTool3({
  name: "add_timeline_entry",
  title: "Add timeline entry",
  description: "Add a dated event to the signed-in user's case timeline.",
  inputSchema: {
    title: z3.string().trim().min(1).max(200).describe("Short event title."),
    event_date: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Event date as YYYY-MM-DD."),
    description: z3.string().trim().max(4e3).optional().describe("Optional details about the event.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, event_date, description }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("timeline_entries").insert({ user_id: ctx.getUserId(), title, event_date, description: description ?? null }).select("id, title, event_date, description").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Added timeline entry "${data.title}" on ${data.event_date}.` }],
      structuredContent: { entry: data }
    };
  }
});

// src/lib/mcp/tools/list-notes.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var list_notes_default = defineTool4({
  name: "list_notes",
  title: "List notes",
  description: "List the signed-in user's private case notes, newest first.",
  inputSchema: {
    limit: z4.number().int().min(1).max(100).optional().describe("Maximum notes to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("notes").select("id, title, content, created_at, updated_at").order("updated_at", { ascending: false }).limit(limit ?? 25);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { notes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-note.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.25.76";
var create_note_default = defineTool5({
  name: "create_note",
  title: "Create note",
  description: "Create a private case note for the signed-in user.",
  inputSchema: {
    title: z5.string().trim().min(1).max(200).describe("Note title."),
    content: z5.string().trim().max(2e4).optional().describe("Note body text.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, content }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("notes").insert({ user_id: ctx.getUserId(), title, content: content ?? null }).select("id, title, content").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Created note "${data.title}".` }],
      structuredContent: { note: data }
    };
  }
});

// src/lib/mcp/tools/list-evidence.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z6 } from "npm:zod@^3.25.76";
var list_evidence_default = defineTool6({
  name: "list_evidence",
  title: "List evidence records",
  description: "List metadata for documents saved in the signed-in user's evidence vault. File contents are not returned.",
  inputSchema: {
    limit: z6.number().int().min(1).max(100).optional().describe("Maximum records to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("evidence").select("id, title, description, document_date, source, system_involved, relevance_notes, file_type, created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { evidence: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "keeirvtfrvyqtmkonsru";
var mcp_default = defineMcp({
  name: "decoded-justice",
  title: "Decoded Justice",
  version: "0.1.0",
  instructions: "Tools for Decoded Justice, a trauma-aware civil rights documentation workspace (educational use only, not legal advice). Read and add the signed-in user's cases, timeline entries, notes, and evidence metadata. Never give legal advice or predict outcomes.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_cases_default,
    list_timeline_entries_default,
    add_timeline_entry_default,
    list_notes_default,
    create_note_default,
    list_evidence_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
