-- Initial directory seed.
-- These records are intentionally marked needs_verification so the app does not
-- present the seed as an endorsement or as a current licensing determination.

insert into public.directory_entries
(name,entry_type,firm_or_org,city,state,county,counties_served,practice_areas,fee_types,website_url,intake_phone,intake_email,accepts_case_builder_summary,active_listing,verification_status,source_url,source_type,last_verified_at,verification_note)
values
('James Bible','Private Attorney','James Bible Law Group','Bellevue','WA','King',ARRAY['King','Pierce','Snohomish'],ARRAY['Civil Rights','Police Misconduct'],ARRAY['Verify Fees'],'https://biblelawgroup.com','(425) 519-3675','james@biblelawgroup.com',false,true,'needs_verification','https://wsba.org/','WSBA/public web','2026-09-22','Source list needs periodic WSBA recheck.'),
('Victoria L. Vreeland','Private Attorney','Vreeland Law','Bellevue','WA','King',ARRAY['King','Pierce','Snohomish'],ARRAY['Civil Rights','Employment Discrimination','Disability Rights'],ARRAY['Verify Fees'],'https://vreeland-law.com','(425) 626-2401','info@vreeland-law.com',false,true,'needs_verification','https://wsba.org/','WSBA/public web','2026-09-22','Source list needs periodic WSBA recheck.'),
('Jordan Taren','Private Attorney','Taren Law Group PLLC','Seattle','WA','King',ARRAY['King','Pierce','Snohomish'],ARRAY['Civil Rights','Police Misconduct','Housing Discrimination','Employment Discrimination','Disability Rights'],ARRAY['Verify Fees'],'https://tarenlaw.com','(206) 622-1604','admin@tarenlaw.com',false,true,'needs_verification','https://tarenlaw.com','Firm website + public legal sources','2026-09-22','Practice scope and contact details should be rechecked before publication refresh.'),
('Edwin Budge','Private Attorney','Budge & Heipt PLLC','Seattle','WA','King',ARRAY['King','Pierce','Snohomish'],ARRAY['Civil Rights','Police Misconduct'],ARRAY['Free Consultation','Verify Fees'],'https://budgeandheipt.com','(206) 624-3060',null,false,true,'needs_verification','https://budgeandheipt.com','Firm website + public legal sources','2026-09-22','Initial consultation terms should be confirmed at source.'),
('Erik J. Heipt','Private Attorney','Budge & Heipt PLLC','Seattle','WA','King',ARRAY['King','Pierce','Snohomish'],ARRAY['Civil Rights','Police Misconduct'],ARRAY['Free Consultation','Verify Fees'],'https://budgeandheipt.com','(206) 624-3060',null,false,true,'needs_verification','https://budgeandheipt.com','Firm website + public legal sources','2026-09-22','Initial consultation terms should be confirmed at source.'),
('Raymond Delos Reyes','Private Attorney','Delos Reyes Law, LLC','Seattle','WA','King',ARRAY['King'],ARRAY['Family Defense'],ARRAY['Verify Fees'],'https://www.rdelosreyeslaw.com','(425) 961-5950','raymond@rdelosreyeslaw.com',false,true,'needs_verification','https://www.rdelosreyeslaw.com','Firm website + public legal sources','2026-09-22','Private representation and public-defense pathways are distinct; verify scope.'),
('King County Family Defense','State Agency','King County Department of Public Defense','Seattle','WA','King',ARRAY['King'],ARRAY['Family Defense'],ARRAY['Pro Bono / Legal Aid'],'https://kingcounty.gov/en/dept/dpd/about-public-defense/practice-areas/family-defense','(206) 477-9727',null,false,true,'needs_verification','https://kingcounty.gov/en/dept/dpd/about-public-defense/practice-areas/family-defense','Official agency source','2026-09-22','Eligibility-based public defense; not a private attorney referral.'),
('Nicholle Mineiro','Private Attorney','Mineiro Law PLLC','Bellevue','WA','King',ARRAY['King','Snohomish','Pierce'],ARRAY['Disability Rights'],ARRAY['Verify Fees'],'https://www.mlp-law.net','(425) 300-2589','nicholle@mlp-law.net',false,true,'needs_verification','https://www.mlp-law.net','Firm website + public legal sources','2026-09-22','Current fee terms should be confirmed directly.'),
('MacDonald Hoague & Bayless','Private Attorney','MacDonald Hoague & Bayless','Seattle','WA','King',ARRAY['King','Pierce','Snohomish'],ARRAY['Civil Rights','Police Misconduct','Housing Discrimination','Employment Discrimination','Disability Rights'],ARRAY['Verify Fees'],'https://www.mhb.com','(206) 622-1604',null,false,true,'needs_verification','https://www.mhb.com','Firm website + public legal sources','2026-09-22','Matter-specific fee terms should be confirmed directly.'),
('Eastside Legal Assistance Program','Legal Aid','Eastside Legal Assistance Program (ELAP)','Bellevue','WA','King',ARRAY['King'],ARRAY['Housing Discrimination','Family Defense','Disability Rights','Employment Discrimination'],ARRAY['Pro Bono / Legal Aid'],'https://www.elap.org','(425) 747-7274',null,false,true,'needs_verification','https://www.elap.org','Official organization source','2026-09-22','Eligibility and scope vary by program/clinic.'),
('Northwest Justice Project','Legal Aid','Northwest Justice Project','Seattle','WA','Statewide',ARRAY['Statewide'],ARRAY['Housing Discrimination','Family Defense','Disability Rights','Employment Discrimination'],ARRAY['Pro Bono / Legal Aid'],'https://nwjustice.org','1-888-201-1012',null,false,true,'needs_verification','https://www.washingtonlawhelp.org/en/get-legal-help','Official public legal-aid sources','2026-09-22','Eligibility, subject matter, location, and capacity determine access.'),
('Disability Rights Washington','Advocacy Org','Disability Rights Washington','Seattle','WA','Statewide',ARRAY['Statewide'],ARRAY['Disability Rights','Civil Rights'],ARRAY['Pro Bono / Legal Aid'],'https://www.disabilityrightswa.org','(206) 324-1521',null,false,true,'needs_verification','https://www.disabilityrightswa.org','Official organization source','2026-09-22','Advocacy/intake eligibility and scope should be confirmed directly.');
